name: Run google tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: cmake tests/CMakeLists.txt
    - name: cd
      run: cd tests
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
